#!/bin/bash

echo "Setup of networking for vm's"

echo -n "Gateway interface: "
read gw

# Values
bridge=br0
LAN_IP="172.16.0.1"
LAN_IP_NET="172.16.0.0/24"
LAN_NIC=$bridge
OUT_NIC=$gw

echo "Bridge br0 setup"
ip link set dev "$bridge" down
brctl delbr $bridge
sleep 1
brctl addbr $bridge
sleep 1

ip addr add "$LAN_IP/24" dev "$bridge"

echo "Setting up NAT"

echo 1 > /proc/sys/net/ipv4/ip_forward
# flush all rules
iptables -F
iptables -t nat -F

# NAT
iptables -t nat -A POSTROUTING -s $LAN_IP_NET -o $OUT_NIC -j MASQUERADE
iptables -A FORWARD -j ACCEPT -i $LAN_NIC -s $LAN_IP_NET
iptables -A FORWARD -m conntrack --ctstate ESTABLISHED,RELATED -j ACCEPT

# start dhcp
/etc/init.d/isc-dhcp-server restart
