#!/bin/sh
# register the client to the master
# information is sent on port 1234, nc in listen mode must be running

echo $(ifconfig eth0 | grep "inet addr" | cut -d: -f2 | awk {'print $1}) | nc 172.16.0.1 1234
