#!/bin/sh

EXE=$(basename $1)
NAME=trace-$EXE
TRACE_PATH=$(pwd)/$NAME
if [ -e $TRACE_PATH ]; then
	rm -rf $TRACE_PATH
fi
lttctl -o channel.all.bufnum=8 -o channel.all.bufsize=1048576 -C -w $TRACE_PATH $NAME
sleep 1
$@
sleep 1
lttctl -D $NAME
