#!/usr/bin/env python

from netfilterqueue import NetfilterQueue
from scapy.all import * 
from struct import *

found = False

def print_and_accept(pkt):
    global found
    #print str(type(pkt)) + " " + repr(pkt)
    #import pdb
    #pdb.set_trace()
    ip = IP(pkt.get_payload())
    if (ip.proto == 0x06): # TCP
        tcp = TCP(pkt.get_payload())
        flags = tcp.fields['flags']
        psh = flags & (1 << 3)
        if (psh and not found):
            print "psh and not found, drop packet"
            found = True
            pkt.drop()
            return
        elif (psh and found):
            print "psh and found, accept packet"
    pkt.accept()

nfqueue = NetfilterQueue()
nfqueue.bind(1, print_and_accept)
try:
    nfqueue.run()
except KeyboardInterrupt:
    print
