#!/usr/bin/env python

from netfilterqueue import NetfilterQueue
from scapy.all import * 
from struct import *

found = False

#import pdb

def print_and_accept(pkt):
    global found
    #print str(type(pkt)) + " " + repr(pkt)
    print pkt
    #import pdb
    ip = IP(pkt.get_payload())
    if (ip.proto == 0x06): # TCP
        tcp = TCP(pkt.get_payload())
        flags = tcp.fields['flags']
        psh = flags & (1 << 3)
#        sport = tcp.getfieldval("sport")
#        dport = tcp.getfieldval("dport")
#        saddr = ip.src
#        daddr = ip.dst
#        print str(saddr) + ":" + str(sport) + " > " + str(daddr) + ":" + str(dport)
        if (psh and not found):
            print "psh and not found, drop packet"
            found = True
            pkt.drop()
            return
        elif (psh and found):
            print "psh and found, accept packet"
    pkt.accept()

#subprocess.call(["iptables",  "-A", "INPUT", "-j", "NFQUEUE", "--queue-num", "1"])

nfqueue = NetfilterQueue()
nfqueue.bind(1, print_and_accept)
try:
    nfqueue.run()
except KeyboardInterrupt:
    pass
print "tcploss quit"
#subprocess.call(["iptables", "-D", "INPUT", "1"])
